### PR TITLE
fixes #12 treat infra/pause container the same as other containers and filter t…

### LINKED ISSUE #12: research 0 values on cluster, namespace and pod cpu.usage_rate
**Description**
Even though there is load being generated by a pod container, pods, namespaces and clusters show 0 for cpu.usage_rate.

**Steps to reproduce:**
Monitor your kubernetes cluster

**Describe the results you received:**
cpu.usage_rate is 0 

**Describe the results you expected:**
cpu.usage_rate is greater than 0

### PR DESCRIPTION
**Pull request by yahonggu**
…hem out during the sink operations

### CODE REVIEW

File: metrics/sources/kubelet/kubelet_test.go [hunk 1]
```diff
@@ -199,8 +199,9 @@ func TestDecodeMetrics5(t *testing.T) {
 	c1.Spec.Labels[kubernetesContainerLabel] = "POD"
 	c1.Spec.Labels[kubernetesPodNameLabel] = "testnamespace/testPodName"
 	metricSetKey, metricSet := kMS.decodeMetrics(&c1)
-	assert.Equal(t, metricSetKey, "namespace:testnamespace/pod:testPodName")
-	assert.Equal(t, metricSet.Labels[core.LabelMetricSetType.Key], core.MetricSetTypePod)
+	// We don't treat infra/pause container differently to get pod aggregator to work correctly
```
Comment (TheConnMan) [inline metrics/sources/kubelet/kubelet_test.go]: Can you remove these instead of commenting out? No reason to keep them in source if they're not used.

Comment (yahonggu) [reply metrics/sources/kubelet/kubelet_test.go]: done.

**Review by TheConnMan — APPROVED** [review]
